language: go

go:
  - 1.15.x
  - 1.x

go_import_path: github.com/vulcand/oxy

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - GO111MODULE=on

before_install:
  - GO111MODULE=off go get -u golang.org/x/lint/golint
  - GO111MODULE=off go get -u github.com/client9/misspell/cmd/misspell

install:
  - go mod tidy
  - git diff --exit-code go.mod go.sum
